#@ load("@ytt:data", "data")

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ "workshopenvironments.training.{}".format(data.values.operator.apiGroup)
spec:
  scope: Cluster
  group: #@ "training.{}".format(data.values.operator.apiGroup)
  names:
    plural: workshopenvironments
    singular: workshopenvironment
    kind: WorkshopEnvironment
    categories:
    - #@ data.values.operator.namePrefix
    - #@ "{}-training".format(data.values.operator.namePrefix)
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - workshop
              properties:
                workshop:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                request:
                  type: object
                  required:
                  - enabled
                  properties:
                    enabled:
                      type: boolean
                    token:
                      type: string
                    namespaces:
                      type: array
                      items:
                        type: string
                session:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    ingress:
                      type: object
                      properties:
                        domain:
                          type: string
                        protocol:
                          type: string
                        secret:
                          type: string
                        class:
                          type: string
                    env:
                      type: array
                      items:
                        type: object
                        required:
                        - name
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                environment:
                  type: object
                  properties:
                    objects:
                      type: array
                      items:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    secrets:
                      type: array
                      items:
                        type: object
                        required:
                        - namespace
                        - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                registry:
                  type: object
                  required:
                  - host
                  properties:
                    host:
                      type: string
                    namespace:
                      type: string
                analytics:
                  type: object
                  properties:
                    google:
                      type: object
                      required:
                      - trackingId
                      properties:
                        trackingId:
                          type: string
                    clarity:
                      type: object
                      required:
                      - trackingId
                      properties:
                        trackingId:
                          type: string
                    amplitude:
                      type: object
                      required:
                      - trackingId
                      properties:
                        trackingId:
                          type: string
                theme:
                  type: object
                  properties:
                    name:
                      type: string
                cookies:
                  type: object
                  properties:
                    domain:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                #@yaml/text-templated-strings
                (@= data.values.operator.statusKey @):
                  type: object
                  properties:
                    phase:
                      type: string
                    message:
                      type: string
                    namespace:
                      type: string
                    secrets:
                      type: object
                      properties:
                        ingress:
                          type: array
                          items:
                            type: string
                        registry:
                          type: array
                          items:
                            type: string
                    workshop:
                      type: object
                      required:
                      - name
                      - uid
                      - generation
                      - spec
                      properties:
                        name:
                          type: string
                        uid:
                          type: string
                        generation:
                          type: integer
                        spec:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
      - name: Workshop
        type: string
        priority: 0
        description: The name of the workshop definition.
        jsonPath: .spec.workshop.name
      - name: URL
        type: string
        priority: 0
        description: URL for further information on the workshop.
        jsonPath: #@ ".status.{}.workshop.spec.url".format(data.values.operator.statusKey)
      - name: Status
        type: string
        priority: 0
        description: Status of workshop environment deployment.
        jsonPath: #@ ".status.{}.phase".format(data.values.operator.statusKey)
      - name: Message
        type: string
        priority: 0
        description: Status message.
        jsonPath: #@ ".status.{}.message".format(data.values.operator.statusKey)
