#@ load("@ytt:data", "data")

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ "workshopallocations.training.{}".format(data.values.operator.apiGroup)
spec:
  scope: Cluster
  group: #@ "training.{}".format(data.values.operator.apiGroup)
  names:
    plural: workshopallocations
    singular: workshopallocation
    kind: WorkshopAllocation
    categories:
    - #@ data.values.operator.namePrefix
    - #@ "{}-training".format(data.values.operator.namePrefix)
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - environment
              - session
              properties:
                environment:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                session:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                #@yaml/text-templated-strings
                (@= data.values.operator.statusKey @):
                  type: object
                  properties:
                    phase:
                      type: string
                    message:
                      type: string
      additionalPrinterColumns:
      - name: Environment
        type: string
        priority: 0
        description: The name of the workshop environment.
        jsonPath: .spec.environment.name
      - name: Session
        type: string
        priority: 0
        description: The name of the workshop session.
        jsonPath: .spec.session.name
      - name: Status
        type: string
        priority: 0
        description: Status of workshop allocation.
        jsonPath: #@ ".status.{}.phase".format(data.values.operator.statusKey)
      - name: Message
        type: string
        priority: 0
        description: Status message.
        jsonPath: #@ ".status.{}.message".format(data.values.operator.statusKey)
