#@ load("@ytt:data", "data")

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ "workshoprequests.training.{}".format(data.values.operator.apiGroup)
spec:
  scope: Namespaced
  group: #@ "training.{}".format(data.values.operator.apiGroup)
  names:
    plural: workshoprequests
    singular: workshoprequest
    kind: WorkshopRequest
    categories:
    - #@ data.values.operator.namePrefix
    - #@ "{}-training".format(data.values.operator.namePrefix)
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - environment
              properties:
                environment:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                    token:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                #@yaml/text-templated-strings
                (@= data.values.operator.statusKey @):
                  type: object
                  properties:
                    phase:
                      type: string
                    url:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                    session:
                      type: object
                      properties:
                        kind:
                          type: string
                        apiVersion:
                          type: string
                        name:
                          type: string
                        uid:
                          type: string
      additionalPrinterColumns:
      - name: URL
        type: string
        priority: 0
        description: The URL to access the workshop.
        jsonPath: #@ ".status.{}.url".format(data.values.operator.statusKey)
      - name: Username
        type: string
        priority: 0
        description: The username to access the workshop.
        jsonPath: #@ ".status.{}.username".format(data.values.operator.statusKey)
      - name: Password
        type: string
        priority: 0
        description: The password to access the workshop.
        jsonPath: #@ ".status.{}.password".format(data.values.operator.statusKey)
      - name: Status
        type: string
        priority: 0
        description: Status of workshop request.
        jsonPath: #@ ".status.{}.phase".format(data.values.operator.statusKey)
