#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Service", "metadata": {"name": "envoy"}})
---
spec:
  type: #@ data.values.service.type
  #@ if/end data.values.service.type=="ClusterIP":
  #@overlay/remove
  externalTrafficPolicy:
