apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: config/_ytt_lib/metacontroller/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/metacontroller/metacontroller
          ref: refs/tags/v4.2.0
        includePaths:
          - "manifests/production/**"
        excludePaths:
          - "**/manifests/production/kustomization.yaml"
        newRootPath: manifests/production
  - path: config/_ytt_lib/kyverno/upstream
    contents:
      - path: "."
        githubRelease:
          slug: kyverno/kyverno
          tag: v1.9.2
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
        includePaths:
          - install.yaml
  - path: config/_ytt_lib/cert-manager
    contents:
      - path: "."
        git:
          url: https://github.com/failk8s-packages/cert-manager-package
          ref: develop #1.12.0
        newRootPath: src/bundle/config
  - path: config/_ytt_lib/contour #config/_ytt_lib/contour/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/failk8s-packages/contour-package # https://github.com/projectcontour
          ref: develop #v1.26.1
        newRootPath: src/bundle/config # examples/contour
  - path: config/_ytt_lib/external-dns
    contents:
      - path: "."
        git:
          url: https://github.com/failk8s-packages/external-dns-package
          ref: develop
        newRootPath: src/bundle/config
  - path: config/_ytt_lib/certs
    contents:
      - path: "."
        git:
          url: https://github.com/failk8s-packages/certs-package
          ref: develop
        newRootPath: src/bundle/config

  # - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-restricted/_ytt_lib/upstream
  #   contents:
  #     - path: "."
  #       git:
  #         url: https://github.com/kyverno/policies
  #         ref: origin/release-1.9

  #       includePaths:
  #         - "pod-security/restricted/**"

  #       excludePaths:
  #         - "**/kustomization.yaml"
  #         - "**/kyverno-test.yaml"
  #         - "**/resource.yaml"

  # - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-baseline/_ytt_lib/upstream
  #   contents:
  #     - path: "."
  #       git:
  #         url: https://github.com/kyverno/policies
  #         ref: origin/release-1.9

  #       includePaths:
  #         - "pod-security/baseline/**"

  #       excludePaths:
  #         - "**/kustomization.yaml"
  #         - "**/kyverno-test.yaml"
  #         - "**/resource.yaml"

  # - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-policies/_ytt_lib/upstream
  #   contents:
  #     - path: "."
  #       git:
  #         url: https://github.com/kyverno/policies
  #         ref: origin/release-1.7

  #       includePaths:
  #         - "best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.yaml"
  #         - "best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.yaml"
  #         - "best-practices/restrict-service-external-ips/restrict-service-external-ips.yaml"
  #         - "best-practices/restrict_node_port/restrict_node_port.yaml"
  #         - "nginx-ingress/nginx-custom-snippets/disallow-custom-snippets.yaml"
  #         - "nginx-ingress/nginx_annotation_checks/restrict-annotations.yaml"
  #         - "nginx-ingress/nginx_path_checks/restrict-path.yaml"
  #         - "other/disallow_localhost_services/disallow_localhost_services.yaml"
  #         - "other/prevent-cr8escape/prevent-cr8escape.yaml"
  #         - "other/restrict_ingress_defaultbackend/restrict_ingress_defaultbackend.yaml"
  #         - "other/restrict_loadbalancer/restrict_loadbalancer.yaml"
  #         - "other/unique-ingress-host-and-path/unique-ingress-host-and-path.yaml"
