#@ load("rules.star", "check_all")

#@data/values-schema
#@schema/validation ("check compliance of values", check_all)
---
#@schema/desc "Underlying infrastructure provider."
#@schema/validation one_of=["aws", "gcp", "azure", "kind", "minikube", "custom"]
infraProvider: "custom"

#@schema/desc "Name of the namespace to use"
namespace: projectcontour
#@schema/desc "Should the namespace be created"
createNamespace: true

#@schema/desc "Contour dpeloyment configuration"
#@schema/nullable
contour:
  replicas: 1

#@schema/desc "Envoy service configuration"
service:
  #@schema/validation one_of=["ClusterIP", "LoadBalancer"]
  type: LoadBalancer
  useHostPorts: true

#@schema/desc "Configuration for externaldns"
#@schema/nullable
externaldns:
  domains:
    - ""

#@schema/desc "Configuration for the Contour ingress controller"
configFileContents:
  #@schema/default ["HTTP/1.1", "HTTP/2"]
  defaultHttpVersions:
    - ""
