apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: config/ytt/_ytt_lib/metacontroller/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/metacontroller/metacontroller
          ref: refs/tags/v4.11.7 # 4.2.0 was used
        includePaths:
          - "manifests/production/**"
        excludePaths:
          - "**/manifests/production/kustomization.yaml"
        newRootPath: manifests/production
  - path: config/ytt/_ytt_lib/kyverno/upstream
    contents:
      - path: "."
        githubRelease:
          slug: kyverno/kyverno
          tag: v1.11.3 # v1.9.2 was used
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
        includePaths:
          - install.yaml
  - path: config/ytt/_ytt_lib/educates/_ytt_lib/kyverno-restricted/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/kyverno/policies
          ref: origin/release-1.11
        includePaths:
          - "pod-security/restricted/**"
        excludePaths:
          - "**/kustomization.yaml"
          - "**/kyverno-test.yaml"
          - "**/0*.yaml"
          - "**/9*.yaml"
          - "**/pod*.yaml"
          - "**/resource.yaml"
          - "**/artifacthub-pkg.yml"
          - "**/.chainsaw-test"
          - "**/.kyverno-test"
  - path: config/ytt/_ytt_lib/educates/_ytt_lib/kyverno-baseline/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/kyverno/policies
          ref: origin/release-1.11
        includePaths:
          - "pod-security/baseline/**"
        excludePaths:
          - "**/kustomization.yaml"
          - "**/kyverno-test.yaml"
          - "**/0*.yaml"
          - "**/9*.yaml"
          - "**/pod*.yaml"
          - "**/resource.yaml"
          - "**/artifacthub-pkg.yml"
          - "**/.chainsaw-test"
          - "**/.kyverno-test"
  - path: config/ytt/_ytt_lib/educates/_ytt_lib/kyverno-policies/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/kyverno/policies
          ref: origin/release-1.11
        includePaths:
          - "best-practices/disallow-empty-ingress-host/disallow-empty-ingress-host.yaml"
          - "best-practices/disallow-cri-sock-mount/disallow-cri-sock-mount.yaml"
          - "best-practices/restrict-service-external-ips/restrict-service-external-ips.yaml"
          - "best-practices/restrict-node-port/restrict-node-port.yaml"
          - "nginx-ingress/disallow-ingress-nginx-custom-snippets/disallow-ingress-nginx-custom-snippets.yaml"
          - "nginx-ingress/restrict-annotations/restrict-annotations.yaml"
          - "nginx-ingress/restrict-ingress-paths/restrict-ingress-paths.yaml"
          - "other/b-d/disallow-localhost-services/disallow-localhost-services.yaml"
          - "other/m-q/prevent-cr8escape/prevent-cr8escape.yaml"
          #! - "other/res/restrict-ingress-defaultbackend/restrict-ingress-defaultbackend.yaml"
          - "other/res/restrict-loadbalancer/restrict-loadbalancer.yaml"
          #! - "other/s-z/unique-ingress-host-and-path/unique-ingress-host-and-path.yaml"
  - path: config/ytt/_ytt_lib/cert-manager/upstream
    contents:
      - path: .
        githubRelease:
          slug: jetstack/cert-manager
          tag: v1.13.3
          disableAutoChecksumValidation: true
        includePaths:
          - cert-manager.yaml
  - path: config/ytt/_ytt_lib/contour/upstream
    contents:
      - path: .
        git:
          url: https://github.com/projectcontour/contour
          ref: v1.27.0
        newRootPath: examples/contour
  - path: config/ytt/_ytt_lib/external-dns/upstream
    contents:
      - path: .
        git:
          url: https://github.com/kubernetes-sigs/external-dns
          ref: v0.14.0
        includePaths:
          - kustomize/external-dns-*
        newRootPath: kustomize
  #! MOVED CERTS TO THIS REPO
  # - path: config/ytt/_ytt_lib/certs
  #   contents:
  #     - path: "."
  #       git:
  #         url: https://github.com/failk8s-packages/certs-package
  #         ref: develop
  #       newRootPath: src/bundle/config
  #! MOVED EDUCATES TO THIS REPO
  # - path: config/ytt/_ytt_lib/educates/upstream
  #   contents:
  #     - path: "."
  #       git:
  #         url: https://github.com/vmware-tanzu-labs/educates-training-platform
  #         ref: develop
  #       newRootPath: carvel-packages/training-platform/bundle/config
  #       excludePaths:
  #         - "_ytt_lib/**"
  #         - "01-clusterpolicies.yaml" # Move this to downstream here
