#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: kind
      contour:
        replicas: 1
      configFileContents:
        defaultHttpVersions:
          - "HTTP/1.1"
      service:
        type: ClusterIP
        useHostPorts: true
