#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=lambda i,l,r: "metadata" in l,expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    educates.dev/infra-provider: #@ data.values.clusterInfrastructure.provider
