#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ data.values.certmanager.namespace or assert.fail("data.values.certmanager.namespace can not be empty")
#@ data.values.ingress.namespace or assert.fail("data.values.ingress.namespace can not be empty")
#@ data.values.ingress.ingressClass or assert.fail("data.values.ingress.ingressClass can not be empty")
#@ data.values.domains or assert.fail("data.values.domains can not be empty")

#@ if data.values.certProvider=="local":
#@   data.values.local.rootCA.crt or assert.fail("missing local.rootCA.crt definition")
#@   data.values.local.rootCA.key or assert.fail("missing local.rootCA.key definition")
#@ end

#@ if data.values.certProvider=="provided":
#@   data.values.provided.wildcartCert.crt or assert.fail("data.values.provided.wildcartCert.crt can not be empty")
#@   data.values.provided.wildcartCert.key or assert.fail("data.values.provided.wildcartCert.key can not be empty")
#@ end
