#@data/values-schema
---
#@schema/desc "The namespace in which to deploy cert-manager"
namespace: cert-manager
#@schema/nullable
serviceaccount:
  #@schema/desc "Annotations to set on the cert-manager service account. Annotations must be in annotation format, that is, map[string]string"
  #@schema/type any=True
  annotations:
#@schema/desc "The namespace to use for leader election. Some infra providers can not use the default kube-system"
leaderElectionNamespace: kube-system
