#@ load("@ytt:data", "data")

#@ def azure():
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "azure"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end

#@ def aks():
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "azure"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end
