#@ def gcp(originalValues):
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "gcp"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end

#@ def gke(originalValues):
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "gcp"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end

#@ def gke_autopilot(originalValues):
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "gcp"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end
