#@ load("@ytt:data", "data")

#@ def gcp():
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "gcp"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end

#@ def gke():
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "gcp"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end

#@ def gke_autopilot():
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: "gcp"
      service:
        type: LoadBalancer
  kyverno:
    enabled: true
    settings: {}
  metacontroller:
    enabled: false
    settings: {}
#@ end
