#@ load("@ytt:data", "data")
#@ load("global.lib.yaml", "copy_all_educates_values")

#@ def kind():
clusterInfrastructure:
  provider: kind
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: kind
      contour:
        replicas: 1
      configFileContents:
        defaultHttpVersions:
          - "HTTP/1.1"
      service:
        type: ClusterIP
        useHostPorts: true
  kyverno:
    enabled: true
    settings: {}
  educates:
    enabled: true
    settings: #@ copy_all_educates_values()
clusterSecurity:
  policyEngine: kyverno
#@ end

#@ def minikube():
infraProvider: "minikube"
#@ end

#@ def custom():
#@   return data.values
#@ end
