#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-session-manager".format(data.values.operator.namePrefix)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

#@ if data.values.clusterSecurity.policyEngine == "pod-security-policies":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-session-manager-psp".format(data.values.operator.namePrefix)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ "{}-baseline-psp".format(data.values.operator.namePrefix)
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-image-puller-psp".format(data.values.operator.namePrefix)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ "{}-baseline-psp".format(data.values.operator.namePrefix)
subjects:
- kind: ServiceAccount
  name: image-puller
  namespace: #@ data.values.operator.namespace
#@ end

#@ if data.values.clusterSecurity.policyEngine == "security-context-constraints":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-session-manager-scc".format(data.values.operator.namePrefix)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ "{}-baseline-scc".format(data.values.operator.namePrefix)
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-image-puller-scc".format(data.values.operator.namePrefix)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ "{}-baseline-scc".format(data.values.operator.namePrefix)
subjects:
- kind: ServiceAccount
  name: image-puller
  namespace: #@ data.values.operator.namespace
#@ end
