#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:md5", "md5")
#@ load("/00-package.star", "image_reference", "image_pull_policy")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-manager
  namespace: #@ data.values.operator.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: secrets-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: secrets-manager
    spec:
      serviceAccountName: secrets-manager
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        #! seccompProfile:
        #!   type: RuntimeDefault
      containers:
      - name: operator
        #@ image = image_reference("secrets-manager")
        image: #@ image
        imagePullPolicy: #@ image_pull_policy(image)
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: config
          mountPath: /opt/app-root/config/
        - name: token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: #@ "{}-config".format(data.values.operator.namePrefix)
      - name: token
        secret:
          secretName: secrets-manager-token
